- name: Trying
  hosts: all
  tasks:
  - name: Downloading file
    get_url: 
      url: https://github.com/nikhilgoenkatech/oneAgentInstance.git
      dest: /home/ngoenka/
  - name: Restarting oneagent
    service:
       name: oneagent
       state: restarted
